-- Backup do Esquema Completo - Miga App
-- Este arquivo serve como referência para o banco de dados no Supabase.

-- 1. Tabela de Perfis de Usuários
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY DEFAULT auth.uid(),
    full_name TEXT,
    current_step INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 2. Tabela de Itens do Catálogo
CREATE TABLE IF NOT EXISTS public.catalog_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT,
    image_url TEXT,
    moodboard_reference TEXT,
    is_new BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3. Tabela de Moodboards
CREATE TABLE IF NOT EXISTS public.moodboards (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    title TEXT,
    content JSONB,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela de Mensagens do Chat
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    role TEXT CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 5. Tabela de Ativos/Imagens da IA
CREATE TABLE IF NOT EXISTS public.user_assets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    asset_type TEXT CHECK (asset_type IN ('try-on', 'decoration', 'trend')),
    image_url TEXT NOT NULL,
    prompt_used TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 6. Tabela de Curtidas/Favoritos
CREATE TABLE IF NOT EXISTS public.user_likes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id),
    item_id BIGINT REFERENCES public.catalog_items(id),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, item_id)
);

-- Configuração de RLS (Row Level Security)
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moodboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_likes ENABLE ROW LEVEL SECURITY;

-- Exemplo de Política (Leitura sugerida)
-- CREATE POLICY "Usuários veem seus próprios perfis" ON user_profiles FOR SELECT USING (auth.uid() = id);
